language: node_js
node_js:
- stable
install:
- npm install
cache:
  directories:
  - node_modules
env:
  global:
  - NODE_ENV=test
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: ncmnYmp1DTFlUqWmE7YALLINg3pw6ky/Ztu1vPgfoCf9XCSSHBm+b+lwADyzrsDN1OyeHv8A3GTJSkqlSZ2pAhUXcMPZhcvfwcdu3rLZ7jatDso1S91IOmTIPgJeoNRiilHrBwUNYQxOlBQD3x20bTSoc6UPJIdtLE39MOtabgXfc1e12DTEHP0JNVS0qFutDXIlUYv7Ob0tizFNm9BdBYnOvd/kyFgW0aKMbmJOEMfkzuQbVoAj832n3jruoFmTE1T2mHxq5O0aVzE+DVC5PJxvGI9zQv7G0pbZelJ1mncGmO6Y/m0UfpuI5+f8ZTV+iM4/zkyMJFdCOdO9OlNzM+sPDnOV5bUztqcxZBvsQHJvnm9iYjq3lhcTiAaMJx6fZCtnLBS0n90cyk5tZMiPMgncCAzeZ23fwhNDwEiNDcgSFi82XktPXNpbHmv2O69wXLCKSHD4848cNo8zG8yyMEbNF/zg4HqnFnttyKKoKpQJWuIpk56OAlVWFn8d1yWIksq6AhI7CdBGA9ZTCqT8zrS9OvFJVa8F0DBqnQb9eLQIm3r/0lcq3k5pbNw07laTwdwbmtYCN51ARH6kwIYJneLZNH0avqNZUY2n4nS9aLgx9u/pzqXJe1S0VVVzobM0MFQYvSuegc+YaTTUJrhjPjoiokRGEk/r8kEOXzcjNnU=
  app: wayfarerapi-andela
  on:
    repo: Ucheduk/WayFarer-API
    branch: develop
before_script:
- psql -c 'create database wayfarer_test_db;' -U postgres
- psql -c "ALTER USER postgres PASSWORD 'password'";
- sh ./setup-test-db.sh
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- npm run test:coverage
after_script:
- "./cc-test-reporter -p ./coverage/lcov.info after-build --exit-code $TRAVIS_TEST_RESULT"
notifications:
- email: flase
